import FooterBar from "@/components/FooterBar/FooterBar";
import Navbar from "@/components/NavBar/NavBar";
import type { Metadata } from "next";
import "./globals.css";
import LangContextProvider from "@/context/LangContext";
import LoadContextProvider from "@/context/LoadContext";

export const metadata: Metadata = {
  title: "Finex - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LangContextProvider>
          <LoadContextProvider>
            <Navbar />
            {children}
            <FooterBar />
          </LoadContextProvider>
        </LangContextProvider>
      </body>
    </html>
  );
}
